import { test, expect } from '@playwright/test';

test('recorded user journey test', async ({ page }) => {
  await page.goto('/');
  await page.waitForLoadState('networkidle');
  await page.getByRole('button', { name: 'Start Saving Today' }).click();
  await page.locator('div').filter({ hasText: /^75% guaranteed generation$/ }).nth(1).click();
  await page.getByText('Gujarat Sun ProjectKutch, Gujarat₹4.2per kW/monthLocated in the sunny Kutch').click();
  await page.getByText('Karnataka Green EnergyTumkur, Karnataka₹4.5per kW/monthState-of-the-art solar').click();
  await page.getByRole('heading', { name: 'Karnataka Green Energy' }).click();
  await page.getByRole('button', { name: '10 kW' }).click();
  await page.getByRole('slider', { name: 'Select solar capacity' }).fill('1');
  await page.locator('.mb-8 > .relative').click();
  await page.getByRole('button', { name: '25 kW' }).click();
  await page.getByRole('button', { name: '50 kW' }).click();
  await page.getByRole('button', { name: 'Sign Up to Reserve' }).click();
  await page.getByRole('banner').getByRole('link', { name: 'PowerNetPro' }).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('textbox', { name: '2500' }).click();
  await page.getByRole('textbox', { name: '2500' }).fill('1000');
  await page.getByText('%10%25%50%75%100%').click();
  await page.getByRole('slider').fill('40');
  await page.getByRole('button', { name: 'Get Started Free' }).first().click();
  await page.getByRole('banner').getByRole('link', { name: 'PowerNetPro' }).click();
  await page.getByRole('link', { name: 'Join Now' }).click();
  await page.getByRole('banner').getByRole('link', { name: 'PowerNetPro' }).click();
  await page.getByRole('button', { name: '02 Savings' }).click();
  await page.getByRole('button', { name: '03 Flexibility' }).click();
  await page.getByRole('button', { name: 'Impact' }).click();
  await page.getByRole('button', { name: 'Convenience' }).click();
  await page.getByRole('combobox').first().selectOption('Maharashtra');
  await page.getByRole('combobox').nth(1).selectOption('Adani Electricity');
  await page.getByRole('button', { name: 'Check Availability' }).click();
  await page.getByRole('button', { name: 'Get Started Now' }).nth(1).click();
  await page.getByRole('button', { name: 'Get Started Now' }).nth(1).click();
  await page.getByRole('button', { name: 'Getting Started' }).click();
  await page.getByRole('button', { name: 'Getting Started' }).click();
  await page.getByRole('button', { name: 'Savings', exact: true }).click();
  await page.getByRole('button', { name: 'All Questions' }).click();
  await page.getByRole('button', { name: 'All Questions' }).click();
  await page.getByRole('button', { name: '01 How much can I save on my' }).click();
  await page.getByRole('button', { name: '01 What is Digital Solar and' }).click();
  await page.getByRole('button', { name: '01 What is Digital Solar and' }).click();
  await page.getByRole('button', { name: 'Contact Us' }).click();
  await page.getByRole('button', { name: 'Contact Us' }).click();
  await page.getByRole('button', { name: 'Contact Us' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Contact' }).click();
  await page.getByRole('textbox', { name: 'John Doe' }).click();
  await page.getByRole('textbox', { name: 'John Doe' }).fill('Omkar ');
  await page.getByRole('textbox', { name: 'John Doe' }).press('Tab');
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('omkarkolhe912@gmail.com');
  await page.getByRole('textbox', { name: 'you@example.com' }).press('Tab');
  await page.getByRole('textbox', { name: '+91 98765' }).fill('8180861415');
  await page.getByRole('textbox', { name: '+91 98765' }).press('Tab');
  await page.getByRole('textbox', { name: 'How can we help?' }).fill('Fuck');
  await page.getByRole('textbox', { name: 'How can we help?' }).press('Tab');
  await page.getByRole('textbox', { name: 'Tell us more about your' }).fill('Fuck');
  await page.getByRole('button', { name: 'Send Message' }).click();
  await page.getByRole('banner').getByRole('link', { name: 'PowerNetPro' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('omkarkolhe912@gm');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('omkarkolhe912@gm');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('omkarkolhe912@gmail.com');
  await page.getByRole('button', { name: 'Subscribe' }).click();
  await page.getByText('Scroll to explore100%').click();
  await page.getByText('Scroll to explore100%').click();
  await page.getByText('100%').nth(1).click();
  await page.getByText('Scroll to explore100%').click();
  await page.getByRole('button', { name: 'Back to top' }).click();
  await page.getByRole('link', { name: 'Benefits' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Contact' }).click();
  await page.getByRole('banner').getByRole('link', { name: 'PowerNetPro' }).click();
  await page.locator('#user-menu-button').click();
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('omka');
  await page.getByRole('textbox', { name: 'you@example.com' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'you@example.com' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('omkarkolhe912@gmail.com');
  await page.getByRole('textbox', { name: 'you@example.com' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('123456789');
  await page.getByRole('checkbox', { name: 'Remember me' }).check();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Reserve Capacity' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('link', { name: 'Add More Capacity Expand your' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('link', { name: 'Connect Utility Link your' }).click();
  await page.getByRole('combobox').first().selectOption('Maharashtra');
  await page.getByText('DISCOM (Distribution Company)Select your DISCOMMSEDCLTata PowerAdani Electricity').click();
  await page.getByRole('combobox').nth(1).selectOption('MSEDCL');
  await page.getByRole('textbox', { name: 'Enter your consumer number' }).click();
  await page.getByRole('textbox', { name: 'Enter your consumer number' }).fill('8495623148596');
  await page.getByRole('button', { name: 'Connect Utility' }).click();
  await page.getByRole('link', { name: 'View Bills Track payments and' }).click();
  await page.getByRole('button', { name: 'Add Manually' }).click();
  await page.getByRole('textbox', { name: 'Enter bill number' }).click();
  await page.getByRole('textbox', { name: 'Enter bill number' }).fill('1489632147896+32');
  await page.getByRole('textbox', { name: 'Enter bill number' }).press('Tab');
  await page.getByPlaceholder('0.00').fill('852');
  await page.locator('input[type="date"]').fill('2026-01-19');
  await page.getByRole('textbox', { name: 'e.g., BSES Rajdhani' }).click();
  await page.getByRole('textbox', { name: 'e.g., BSES Rajdhani' }).fill('MESDCL');
  await page.getByRole('button', { name: 'Add Bill', exact: true }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('link', { name: 'Notifications' }).click();
  await page.locator('.w-7.h-7.border-2').first().click();
  await page.locator('label').nth(4).click();
  await page.locator('div:nth-child(2) > .relative.z-10 > .relative.inline-flex > .w-7').click();
  await page.locator('.w-7.h-7.border-2.rounded-full.transition-all.relative.shadow-md.border-gray-300').click();
  await page.getByRole('link', { name: 'Security' }).click();
  await page.getByRole('button', { name: 'Change Password' }).click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByTitle('omkarkolhe912@gmail.com').click();
  await page.getByRole('banner').getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('button', { name: 'Start Earning Credits' }).click();
  await page.getByRole('heading', { name: 'Gujarat Sun Project' }).click();
  await page.getByRole('button', { name: '10 kW' }).click();
  await page.getByRole('button', { name: 'Reserve Now' }).click();
  await page.getByRole('button', { name: 'Complete Payment' }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
});