import type { Metadata } from "next";

// Canonical production origin. Reads from NEXT_PUBLIC_APP_URL so preview
// deploys can opt into their own absolute URLs, but defaults to the live
// domain so OG/Twitter tags resolve correctly even when the env var is unset.
const RAW_SITE_URL =
  (process.env.NEXT_PUBLIC_APP_URL || "https://www.powernetpro.com").trim();

export const SITE_URL = RAW_SITE_URL.replace(/\/+$/, "");
export const SITE_NAME = "PowerNetPro";
export const SITE_LEGAL_NAME = "PowerNetPro Private Limited";
// Generated by app/opengraph-image.tsx at the edge. Replace with a static
// /public/og-default.png and update this constant when a designed asset is
// ready.
export const DEFAULT_OG_IMAGE = "/opengraph-image";
export const TWITTER_HANDLE = "@powernetpro";

export type PageMetadataInput = {
  title: string;
  description: string;
  path: string;
  image?: string;
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
  keywords?: string[];
  noindex?: boolean;
};

/**
 * Build a BreadcrumbList JSON-LD object from an ordered list of
 * `{ name, path }` entries. Emit it inside a page layout via:
 *   <script type="application/ld+json"
 *     dangerouslySetInnerHTML={{ __html: JSON.stringify(buildBreadcrumbJsonLd([...])) }} />
 *
 * The root "Home → /" is always prepended; do not include it in the input.
 */
export function buildBreadcrumbJsonLd(
  trail: Array<{ name: string; path: string }>
) {
  const items = [{ name: "Home", path: "/" }, ...trail];
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((entry, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: entry.name,
      item: `${SITE_URL}${entry.path === "/" ? "" : entry.path}`,
    })),
  };
}

export function buildMetadata(input: PageMetadataInput): Metadata {
  const path = input.path.startsWith("/") ? input.path : `/${input.path}`;
  const url = `${SITE_URL}${path === "/" ? "" : path}`;
  const image = input.image || DEFAULT_OG_IMAGE;
  const absoluteImage = image.startsWith("http") ? image : `${SITE_URL}${image}`;

  return {
    title: input.title,
    description: input.description,
    keywords: input.keywords,
    alternates: {
      canonical: url,
    },
    robots: input.noindex
      ? { index: false, follow: false }
      : { index: true, follow: true },
    openGraph: {
      title: input.title,
      description: input.description,
      url,
      siteName: SITE_NAME,
      type: input.type || "website",
      locale: "en_IN",
      images: [
        {
          url: absoluteImage,
          width: 1200,
          height: 630,
          alt: input.title,
        },
      ],
      ...(input.type === "article"
        ? {
            publishedTime: input.publishedTime,
            modifiedTime: input.modifiedTime,
            authors: input.authors,
          }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: input.title,
      description: input.description,
      images: [absoluteImage],
    },
  };
}
